---
- name: Import Microsoft GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/code stable main
    state: present

- name: Install VSCode
  ansible.builtin.apt:
    name: code
    update_cache: yes
    state: latest


